#
# This is the DASH configuration makefile for Xperia T.
#
SOMC_CFG_SENSORS_ACCEL_BMA250NA_INPUT =yes
SOMC_CFG_SENSORS_GYRO_MPU3050 = yes
SOMC_CFG_SENSORS_COMPASS_AK8972 = yes
SOMC_CFG_SENSORS_LIGHT_LIBALS = yes

